// packages/react/demo/index.tsx
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import { Pagination } from '../dist/'

class Main extends React.Component<{}, {}> {
  private total = 12
  private current1 = 1
  private count = 2

  private current2 = 1
  private mode1 = 1

  render () {
    return (
            <div>
                <a href='https://github.com/plantain-00/pagination-js-component/tree/master/packages/react/demo' target='_blank'>the source code of the demo</a>
                <h3>default mode:</h3>
                <div className='default-mode'>
                    <Pagination total={this.total}
                        current={this.current1}
                        count={this.count}
                        jump={page => this.jump1(page)}>
                    </Pagination>
                </div>
                <br />
                <h3>mode 1:</h3>
                <div className='mode-1'>
                    <Pagination total={this.total}
                        current={this.current2}
                        count={this.count}
                        mode={this.mode1}
                        jump={page => this.jump2(page)}>
                    </Pagination>
                </div>
            </div>
    )
  }
  private jump1 (page: number) {
    this.current1 = page
    this.setState({ current1: this.current1 })
  }
  private jump2 (page: number) {
    this.current2 = page
    this.setState({ current2: this.current2 })
  }
}

ReactDOM.render(<Main />, document.getElementById('container'))

// packages/angular/demo/main.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app',
  template: `
    <div>
        <a href="https://github.com/plantain-00/pagination-js-component/tree/master/packages/angular/demo" target="_blank">the source code of the demo</a>
        <h3>default mode:</h3>
        <div class="default-mode">
            <pagination [total]="total"
                [current]="current1"
                [count]="count"
                (jump)="jump1($event)">
            </pagination>
        </div>
        <br/>
        <h3>mode 1:</h3>
        <div class="mode-1">
            <pagination [total]="total"
                [current]="current2"
                [count]="count"
                [mode]="mode1"
                (jump)="jump2($event)">
            </pagination>
        </div>
    </div>
    `
})
export class MainComponent {
  total = 12
  current1 = 1
  count = 2

  current2 = 1
  mode1 = 1

  jump1 (page: number) {
    this.current1 = page
  }
  jump2 (page: number) {
    this.current2 = page
  }
}
