// packages/angular/src/index.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core'

import * as common from 'pagination-js-component'

import { indexTemplateHtml } from './variables'

/**
 * @public
 */
@Component({
  selector: 'pagination',
  template: indexTemplateHtml
})
export class PaginationComponent {
  @Input()
  total!: number
  @Input()
  current!: number
  @Input()
  count!: number
  @Input()
  mode?: number

  @Output()
  jump = new EventEmitter<number>()

  get pages() {
    return common.getPages(this.current, this.total, this.count, this.mode)
  }

  jumpTo(page: number) {
    this.jump.emit(page)
  }

  trackBy(page: common.Page, index: number) {
    return index
  }
}

// packages/react/src/index.tsx
import * as React from 'react'
import * as common from 'pagination-js-component'
export * from 'pagination-js-component'

/**
 * @public
 */
export class Pagination extends React.PureComponent<{
  total: number;
  current: number;
  count: number;
  mode?: number;
  jump: (page: number) => void;
}, { hovered: boolean }> {
  render () {
    const list = common.getPages(this.props.current, this.props.total, this.props.count, this.props.mode).map(page => {
      if (page.disabled) {
        return (
                    <li key={page.text}>
                        <span>{page.text}</span>
                    </li>
        )
      } else {
        return (
                    <li key={page.text}>
                        <a href='javascript:void(0)' className={page.className} onClick={e => this.jumpTo(page.value)}>{page.text}</a>
                    </li>
        )
      }
    })
    return (
            <ul className='pagination'>
                {list}
            </ul>
    )
  }
  private jumpTo (page: number) {
    this.props.jump(page)
  }
}
